-- Split carrier/company users away from internal Users.
--
-- Goal:
-- - public."Users" remains for internal employees/managers.
-- - public."ExternalUsers" stores carrier dispatchers/company users.
-- - public."VehicleAvailability" points to ExternalUsers, not Users.
--
-- Run once in the Supabase SQL editor.

begin;

create table if not exists public."ExternalUsers" (
    id int4 generated by default as identity primary key,
    "companyId" int8 not null references public."Companies"(id) on delete cascade,
    "userName" varchar not null unique,
    password text not null,
    role text not null default 'dispatcher'
        check (role in ('dispatcher', 'company_admin')),
    status text not null default 'active'
        check (status in ('active', 'suspended', 'pending')),
    "refreshToken" text,
    "createdAt" timestamp not null default now(),
    "updatedAt" timestamp not null default now()
);

-- If you already temporarily stored carrier users in Users with companyId/role,
-- preserve their ids so existing VehicleAvailability rows can still point to
-- the same user id after the foreign key is moved.
insert into public."ExternalUsers" (
    id,
    "companyId",
    "userName",
    password,
    role,
    status,
    "refreshToken",
    "createdAt",
    "updatedAt"
)
select
    id,
    "companyId",
    "userName",
    password,
    case
        when role in ('dispatcher', 'company_admin') then role
        else 'dispatcher'
    end,
    coalesce(status, 'active'),
    "refreshToken",
    "createdAt",
    "updatedAt"
from public."Users"
where "companyId" is not null
on conflict (id) do nothing;

-- Keep ExternalUsers identity sequence ahead of any explicitly copied ids.
select setval(
    pg_get_serial_sequence('public."ExternalUsers"', 'id'),
    greatest(coalesce((select max(id) from public."ExternalUsers"), 0), 1),
    true
);

-- Rename the availability creator column to make the relationship explicit.
alter table public."VehicleAvailability"
    rename column "createdByUserId" to "createdByExternalUserId";

-- Drop any old foreign key that pointed VehicleAvailability.createdByExternalUserId
-- to Users. Constraint names can vary, so discover them dynamically.
do $$
declare
    constraint_record record;
begin
    for constraint_record in
        select con.conname
        from pg_constraint con
        join pg_class rel on rel.oid = con.conrelid
        join pg_namespace nsp on nsp.oid = rel.relnamespace
        join unnest(con.conkey) with ordinality as cols(attnum, ordinality) on true
        join pg_attribute att on att.attrelid = rel.oid and att.attnum = cols.attnum
        where nsp.nspname = 'public'
          and rel.relname = 'VehicleAvailability'
          and con.contype = 'f'
          and att.attname = 'createdByExternalUserId'
    loop
        execute format(
            'alter table public."VehicleAvailability" drop constraint %I',
            constraint_record.conname
        );
    end loop;
end $$;

alter table public."VehicleAvailability"
    add constraint vehicle_availability_created_by_external_user_fk
    foreign key ("createdByExternalUserId")
    references public."ExternalUsers"(id)
    on delete restrict;

-- Remove copied external users from the internal Users table.
-- The quotation guard avoids deleting any row that somehow owns quotations.
delete from public."Users" u
where u."companyId" is not null
  and not exists (
      select 1
      from public."Quotations" q
      where q."userId" = u.id
  );

-- Restore Users to internal-user shape.
drop index if exists public.users_company_idx;

alter table public."Users"
    drop constraint if exists users_role_check,
    drop constraint if exists users_status_check;

alter table public."Users"
    drop column if exists "companyId",
    drop column if exists role,
    drop column if exists status;

create index if not exists external_users_company_idx
    on public."ExternalUsers" ("companyId");

create index if not exists vehicle_availability_external_user_idx
    on public."VehicleAvailability" ("createdByExternalUserId");

commit;
